[package]
name = "openrgb-temp-sync-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systemstat = "0.2.2"
openrgb = "0.1.2"
tokio = { version = "1.22.0", features = ["full"] }
